using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using UM_Project.Data;
using UM_Project.Services.Interfaces;

namespace UM_Project.Services
{
    public class TranscriptPdfService : ITranscriptPdfService
    {
        private readonly ApplicationDbContext _context;

        public TranscriptPdfService(ApplicationDbContext context) => _context = context;

        public async Task<byte[]> GenerateTranscriptAsync(int studentId)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var student = await _context.Students
                .Include(s => s.Department)
                .FirstOrDefaultAsync(s => s.StudentId == studentId)
                ?? throw new InvalidOperationException("Student not found.");

            var grades = await _context.Grades
                .Include(g => g.Course)
                .Where(g => g.StudentId == studentId)
                .OrderBy(g => g.Course!.CourseName)
                .ToListAsync();

            var avg = grades.Any() ? grades.Average(g => g.Value) : 0;

            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Column(col =>
                    {
                        col.Item().Text("University Manager — Official Transcript").Bold().FontSize(18).FontColor(Colors.Red.Darken2);
                        col.Item().PaddingTop(8).Text($"Issued: {DateTime.Now:MMMM d, yyyy}");
                    });

                    page.Content().PaddingVertical(20).Column(col =>
                    {
                        col.Item().Text($"Student: {student.FullName}").Bold();
                        col.Item().Text($"Student #: {student.StudentNumber}");
                        col.Item().Text($"Department: {student.Department?.DepartmentName ?? "—"}");
                        col.Item().Text($"Email: {student.Email}");
                        col.Item().PaddingTop(16).Text("Course grades").Bold().FontSize(14);

                        col.Item().PaddingTop(8).Table(table =>
                        {
                            table.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(2);
                                c.RelativeColumn(3);
                                c.ConstantColumn(60);
                                c.ConstantColumn(80);
                            });
                            table.Header(h =>
                            {
                                h.Cell().Background(Colors.Grey.Lighten3).Padding(4).Text("Code").Bold();
                                h.Cell().Background(Colors.Grey.Lighten3).Padding(4).Text("Course").Bold();
                                h.Cell().Background(Colors.Grey.Lighten3).Padding(4).Text("Grade").Bold();
                                h.Cell().Background(Colors.Grey.Lighten3).Padding(4).Text("Date").Bold();
                            });
                            foreach (var g in grades)
                            {
                                table.Cell().Padding(4).Text(g.Course?.CourseCode ?? "—");
                                table.Cell().Padding(4).Text(g.Course?.CourseName ?? "—");
                                table.Cell().Padding(4).Text(g.Value.ToString());
                                table.Cell().Padding(4).Text(g.DateRecorded.ToLocalTime().ToString("dd/MM/yyyy"));
                            }
                        });

                        col.Item().PaddingTop(12).Text($"Cumulative average: {avg:0.00}").Bold();
                    });

                    page.Footer().AlignCenter().Text(t =>
                    {
                        t.Span("Generated by UM_Project · ");
                        t.Span("For official use only").Italic();
                    });
                });
            });

            return doc.GeneratePdf();
        }
    }
}
