$viewsPath = Join-Path $PSScriptRoot '..\Views'
$utf8 = New-Object System.Text.UTF8Encoding $true
$replacements = [ordered]@{
    'class="form-label">Course</label>' = 'class="form-label">@Localizer["Label_Course"]</label>'
    'class="form-label">Student</label>' = 'class="form-label">@Localizer["Label_Student"]</label>'
    'class="form-label">Department</label>' = 'class="form-label">@Localizer["Label_Department"]</label>'
    'class="form-label">Professor</label>' = 'class="form-label">@Localizer["Label_Professor"]</label>'
    'class="form-label">Full name</label>' = 'class="form-label">@Localizer["Form_FullName"]</label>'
    'class="form-label">Parent account</label>' = 'class="form-label">@Localizer["Label_ParentAccount"]</label>'
    'class="form-label">Student (child)</label>' = 'class="form-label">@Localizer["Label_StudentChild"]</label>'
    'class="form-label">Parent full name</label>' = 'class="form-label">@Localizer["Label_ParentFullName"]</label>'
    'class="form-label">Parent email (optional)</label>' = 'class="form-label">@Localizer["Label_ParentEmailOptional"]</label>'
    'class="form-label">Add documents</label>' = 'class="form-label">@Localizer["Label_AddDocuments"]</label>'
    '<option value="">Select course</option>' = '<option value="">@Localizer["Form_SelectCourse"]</option>'
    '<option value="">Select department</option>' = '<option value="">@Localizer["Form_SelectDepartment"]</option>'
    '<option value="">Select professor</option>' = '<option value="">@Localizer["Form_SelectProfessor"]</option>'
    '<option value="">Select parent</option>' = '<option value="">@Localizer["Form_SelectParent"]</option>'
    '<option value="">Select student</option>' = '<option value="">@Localizer["Form_SelectStudent"]</option>'
    '<option value="">Select student — use student # if names match</option>' = '<option value="">@Localizer["Form_SelectStudentDisambig"]</option>'
    '<option value="">Select grade</option>' = '<option value="">@Localizer["Form_SelectGrade"]</option>'
    '<option value="">Department</option>' = '<option value="">@Localizer["Label_Department"]</option>'
    '<tr><th>Course</th>' = '<tr><th>@Localizer["Label_Course"]</th>'
    '<tr><th>Grade</th>' = '<tr><th>@Localizer["Table_Grade"]</th>'
    '<tr><th>Day</th>' = '<tr><th>@Localizer["Label_Day"]</th>'
    '<tr><th>Time</th>' = '<tr><th>@Localizer["Label_Time"]</th>'
    '<tr><th>Room</th>' = '<tr><th>@Localizer["Label_Room"]</th>'
    '<tr><th>Student</th>' = '<tr><th>@Localizer["Table_Student"]</th>'
    '<tr><th>Dept</th>' = '<tr><th>@Localizer["Label_Dept"]</th>'
    '<tr><th>Status</th>' = '<tr><th>@Localizer["Label_Status"]</th>'
    '<tr><th>Requested</th>' = '<tr><th>@Localizer["Table_Requested"]</th>'
    '<tr><th>Parent note</th>' = '<tr><th>@Localizer["Table_ParentNote"]</th>'
    '<tr><th>Title</th>' = '<tr><th>@Localizer["Table_Title"]</th>'
    '<tr><th>Due</th>' = '<tr><th>@Localizer["Label_Due"]</th>'
    '<tr><th>Weight</th>' = '<tr><th>@Localizer["Label_Weight"]</th>'
    '<tr><th>Date</th>' = '<tr><th>@Localizer["Table_Date"]</th>'
    '<tr><th>Blocks</th>' = '<tr><th>@Localizer["Label_Blocks"]</th>'
    '<tr><th>Type</th>' = '<tr><th>@Localizer["Label_Type"]</th>'
    '<tr><th>Professor</th>' = '<tr><th>@Localizer["Table_Professor"]</th>'
    '>Reset password</h3>' = '>@Localizer["Label_ResetPassword"]</h3>'
    '<h1>Profile Not Found</h1>' = '<h1>@Localizer["Page_ProfileNotFoundTitle"]</h1>'
    '>Grade & attendance rules</h1>' = '>@Localizer["Label_GradeRules"]</h1>'
    'Minimum grade</label>' = '@Localizer["Label_MinGrade"]</label>'
    'Maximum grade</label>' = '@Localizer["Label_MaxGrade"]</label>'
    'Passing grade</label>' = '@Localizer["Label_PassingGrade"]</label>'
    'Lessons per school day</label>' = '@Localizer["Label_LessonsPerDay"]</label>'
    'Save settings</button>' = '@Localizer["Msg_SaveSettings"]</button>'
    '<dt class="col-sm-3">Department</dt>' = '<dt class="col-sm-3">@Localizer["Label_Department"]</dt>'
    '<dt class="col-sm-3">Professor</dt>' = '<dt class="col-sm-3">@Localizer["Label_Professor"]</dt>'
    'placeholder="Search by name, email, or role..."' = 'placeholder="@Localizer["Search_Users"]"'
    'placeholder="Search student or course..."' = 'placeholder="@Localizer["Search_Enrollments"]"'
    'placeholder="Search course, day, room..."' = 'placeholder="@Localizer["Search_Schedules"]"'
    'placeholder="Search departments..."' = 'placeholder="@Localizer["Search_Departments"]"'
    'placeholder="Search parent, email, or student..."' = 'placeholder="@Localizer["Search_Parents"]"'
    "confirm('Delete?')" = 'confirm(''@Localizer["Confirm_Delete"]'')'
    "confirm('Reject?')" = 'confirm(''@Localizer["Confirm_Reject"]'')'
    "confirm('Remove this document?')" = 'confirm(''@Localizer["Confirm_RemoveDocument"]'')'
    "confirm('Remove this slot?')" = 'confirm(''@Localizer["Confirm_RemoveSlot"]'')'
    "confirm('Reset password to default?')" = 'confirm(''@Localizer["Confirm_ResetPasswordDefault"]'')'
    "confirm('Reset to default password?')" = 'confirm(''@Localizer["Confirm_ResetPasswordDefault"]'')'
    'title="Details"' = 'title="@Localizer["Title_Details"]"'
    'title="Reset password"' = 'title="@Localizer["Label_ResetPassword"]"'
    'title="Edit parent"' = 'title="@Localizer["Title_EditParent"]"'
    'title="Add another child"' = 'title="@Localizer["Title_AddChild"]"'
    'title="Remove link"' = 'title="@Localizer["Title_RemoveLink"]"'
    'title="Remove enrollment"' = 'title="@Localizer["Title_RemoveEnrollment"]"'
    'title="Absent"' = 'title="@Localizer["Label_Absent"]"'
    '<span class="um-badge um-badge-blue">Professor</span>' = '<span class="um-badge um-badge-blue">@Localizer["Role_Professor"]</span>'
    '<span class="um-badge um-badge-green">Student</span>' = '<span class="um-badge um-badge-green">@Localizer["Role_Student"]</span>'
    '<span class="um-badge um-badge-orange">Parent</span>' = '<span class="um-badge um-badge-orange">@Localizer["Role_Parent"]</span>'
    'Scheduled (@Model.Count())' = '@Localizer["Label_Scheduled"] (@Model.Count())'
    'placeholder="Title"' = 'placeholder="@Localizer["Table_Title"]"'
    'placeholder="Description (optional)"' = 'placeholder="@Localizer["Label_Description"] @Localizer["Label_Optional"]"'
    'placeholder="Optional note"' = 'placeholder="@Localizer["Placeholder_OptionalNote"]"'
    'placeholder="Note"' = 'placeholder="@Localizer["Placeholder_Note"]"'
    'placeholder="Fall 2026"' = 'placeholder="@Localizer["Placeholder_Semester"]"'
    'placeholder="Lesson 1"' = 'placeholder="@Localizer["Placeholder_Lesson1"]"'
    'placeholder="Monday"' = 'placeholder="@Localizer["Placeholder_Monday"]"'
    'placeholder="A-101"' = 'placeholder="@Localizer["Placeholder_Room"]"'
    'Document requests</h1>' = '@Localizer["Doc_RequestsTitle"]</h1>'
    'Request official transcripts' = '@Localizer["Doc_RequestsSubtitle"]'
    'Request transcript</h3>' = '@Localizer["Doc_RequestTranscript"]</h3>'
    'Your requests</h3>' = '@Localizer["Doc_YourRequests"]</h3>'
    'Select child</option>' = '@Localizer["Form_SelectStudent"]</option>'
    'Manage all users & assign roles</li>' = '@Localizer["Guide_Admin1"]</li>'
    'Students, professors, parents</li>' = '@Localizer["Guide_Admin2"]</li>'
    'Courses, enrollments, schedules</li>' = '@Localizer["Guide_Admin3"]</li>'
    'Grades & statistics</li>' = '@Localizer["Guide_Admin4"]</li>'
    'View assigned courses</li>' = '@Localizer["Guide_Prof1"]</li>'
    'Record attendance</li>' = '@Localizer["Guide_Prof2"]</li>'
    'Submit & manage grades</li>' = '@Localizer["Guide_Prof3"]</li>'
    'View schedule</li>' = '@Localizer["Guide_Student1"]</li>'
    'View grades</li>' = '@Localizer["Guide_Student2"]</li>'
    "View child's grades</li>" = '@Localizer["Guide_Parent1"]</li>'
    "View child's schedule</li>" = '@Localizer["Guide_Parent2"]</li>'
    'Courses & professors</h3>' = '@Localizer["Label_CoursesAndProfessors"]</h3>'
    'Parents / guardians</h3>' = '@Localizer["Label_ParentsGuardians"]</h3>'
    '>Grades</h3>' = '>@Localizer["Label_GradesSection"]</h3>'
    'Reset login password</h3>' = '@Localizer["Label_ResetPassword"]</h3>'
    'Add parent / guardian now</label>' = '@Localizer["Msg_AddParentCheck"]</label>'
    'Grade (5–10)</label>' = '@Localizer["Form_SelectGradeRange"]</label>'
    '<strong>Student number:</strong>' = '<strong>@Localizer["Label_StudentNumber"]:</strong>'
    '<div class="text-xs text-gray-500 font-bold uppercase">Courses</div>' = '<div class="text-xs text-gray-500 font-bold uppercase">@Localizer["Label_CoursesCount"]</div>'
}
$n = 0
Get-ChildItem $viewsPath -Recurse -Filter '*.cshtml' | ForEach-Object {
    $c = [IO.File]::ReadAllText($_.FullName, $utf8)
    $o = $c
    foreach ($k in $replacements.Keys) { $c = $c.Replace($k, $replacements[$k]) }
    if ($c -ne $o) {
        [IO.File]::WriteAllText($_.FullName, $c, $utf8)
        $n++
    }
}
Write-Host "Updated $n view files."
