$viewsPath = Join-Path $PSScriptRoot '..\Views'
$replacements = [ordered]@{
    'ViewData["PageTitle"] = "Enrollments"' = 'ViewData["PageTitle"] = Localizer["Nav_Enrollments"]'
    'ViewData["PageSubtitle"] = "Student course registrations"' = 'ViewData["PageSubtitle"] = Localizer["Page_Enrollments_Subtitle"]'
    'ViewData["CreateText"] = "New Enrollment"' = 'ViewData["CreateText"] = Localizer["Page_Enrollments_Create"]'
    'ViewData["PageTitle"] = "Parents"' = 'ViewData["PageTitle"] = Localizer["Nav_Parents"]'
    'ViewData["PageSubtitle"] = "Guardians with login email — assign multiple children per parent"' = 'ViewData["PageSubtitle"] = Localizer["Page_Parents_Subtitle"]'
    'ViewData["CreateText"] = "New parent"' = 'ViewData["CreateText"] = Localizer["Page_Parents_Create"]'
    'ViewData["PageTitle"] = "Grades"' = 'ViewData["PageTitle"] = Localizer["Nav_Grades"]'
    'ViewData["PageSubtitle"] = "Student grades and pass/fail status"' = 'ViewData["PageSubtitle"] = Localizer["Page_Grades_Subtitle"]'
    'ViewData["CreateText"] = "Assign Grade"' = 'ViewData["CreateText"] = Localizer["Page_Grades_Create"]'
    'ViewData["PageSubtitle"] = "Faculty members and department assignments"' = 'ViewData["PageSubtitle"] = Localizer["Page_Professors_Subtitle"]'
    'ViewData["PageTitle"] = "Departments"' = 'ViewData["PageTitle"] = Localizer["Nav_Departments"]'
    'ViewData["PageSubtitle"] = "Organize academic departments"' = 'ViewData["PageSubtitle"] = Localizer["Page_Departments_Subtitle"]'
    'ViewData["PageTitle"] = "Courses"' = 'ViewData["PageTitle"] = Localizer["Nav_Courses"]'
    'ViewData["PageSubtitle"] = "Course catalog, credits, and professor assignments"' = 'ViewData["PageSubtitle"] = Localizer["Page_Courses_Subtitle"]'
    'ViewData["PageTitle"] = "Schedules"' = 'ViewData["PageTitle"] = Localizer["Nav_Schedules"]'
    'ViewData["PageSubtitle"] = "Class times, rooms, and weekly timetable"' = 'ViewData["PageSubtitle"] = Localizer["Page_Schedules_Subtitle"]'
    'ViewData["PageTitle"] = "Users & Roles"' = 'ViewData["PageTitle"] = Localizer["Nav_UsersRoles"]'
    'ViewData["PageSubtitle"] = "SuperAdmin only — manage all accounts, roles (including Admin), and passwords"' = 'ViewData["PageSubtitle"] = Localizer["Page_Users_Subtitle"]'
    'ViewData["CreateText"] = "Add User"' = 'ViewData["CreateText"] = Localizer["Page_Users_Create"]'
    'ViewData["PageTitle"] = "Academic calendar"' = 'ViewData["PageTitle"] = Localizer["Nav_AcademicCalendar"]'
    'ViewData["PageSubtitle"] = "Terms, holidays, exam weeks — blocks professor attendance"' = 'ViewData["PageSubtitle"] = Localizer["Page_Calendar_Subtitle"]'
    'ViewData["PageTitle"] = "Document requests"' = 'ViewData["PageTitle"] = Localizer["Nav_DocumentRequests"]'
    'ViewData["PageSubtitle"] = "Approve transcripts and generate PDF"' = 'ViewData["PageSubtitle"] = Localizer["Page_Documents_Subtitle"]'
    'ViewData["PageTitle"] = "My Class Schedules"' = 'ViewData["PageTitle"] = Localizer["Page_StudentSchedules"]'
    'ViewData["PageTitle"] = "My Course Schedules"' = 'ViewData["PageTitle"] = Localizer["Page_ProfessorSchedules"]'
    'ViewData["PageTitle"] = "My Grades"' = 'ViewData["PageTitle"] = Localizer["Page_MyGrades"]'
    'ViewData["Title"] = "Child''s Grades"' = 'ViewData["Title"] = Localizer["Page_ChildGrades"]'
    'ViewData["Title"] = "Child''s Schedule"' = 'ViewData["Title"] = Localizer["Page_ChildSchedule"]'
    'ViewData["PageTitle"] = "Schedule"' = 'ViewData["PageTitle"] = Localizer["Nav_MySchedule"]'
    'ViewData["Title"] = "Child attendance"' = 'ViewData["Title"] = Localizer["Page_ChildAttendance"]'
    'ViewData["Title"] = "Edit Enrollment"' = 'ViewData["Title"] = Localizer["Page_EditEnrollment"]'
    'ViewData["Title"] = "Link Parent"' = 'ViewData["Title"] = Localizer["Page_LinkParent"]'
    'ViewData["Title"] = "Register Student"' = 'ViewData["Title"] = Localizer["Page_CreateStudent"]'
    'ViewData["Title"] = "Create Professor"' = 'ViewData["Title"] = Localizer["Page_CreateProfessor"]'
    'ViewData["Title"] = "Edit Department"' = 'ViewData["Title"] = Localizer["Page_EditDepartment"]'
    'ViewData["Title"] = "Create Schedule"' = 'ViewData["Title"] = Localizer["Page_CreateSchedule"]'
    'ViewData["Title"] = "Parent Profile"' = 'ViewData["Title"] = Localizer["Page_ParentProfile"]'
    'ViewData["Title"] = "Edit Course"' = 'ViewData["Title"] = Localizer["Page_EditCourse"]'
    'ViewData["Title"] = "Assign Child"' = 'ViewData["Title"] = Localizer["Page_AssignChild"]'
    'ViewData["Title"] = "Edit Parent"' = 'ViewData["Title"] = Localizer["Page_EditParent"]'
    'ViewData["Title"] = "Create Department"' = 'ViewData["Title"] = Localizer["Page_CreateDepartment"]'
    'ViewData["Title"] = "Edit Grade"' = 'ViewData["Title"] = Localizer["Page_EditGrade"]'
    'ViewData["Title"] = "Edit Schedule"' = 'ViewData["Title"] = Localizer["Page_EditSchedule"]'
    'ViewData["Title"] = "Create Course"' = 'ViewData["Title"] = Localizer["Page_CreateCourse"]'
    'ViewData["Title"] = "Edit Student"' = 'ViewData["Title"] = Localizer["Page_EditStudent"]'
    'ViewData["Title"] = "Edit Professor"' = 'ViewData["Title"] = Localizer["Page_EditProfessor"]'
    'ViewData["Title"] = "New Enrollment"' = 'ViewData["Title"] = Localizer["Page_NewEnrollment"]'
    'ViewData["Title"] = "Assign Grade"' = 'ViewData["Title"] = Localizer["Page_AssignGrade"]'
    'ViewData["Title"] = "Create User"' = 'ViewData["Title"] = Localizer["Page_CreateUser"]'
    'placeholder="Search name, email, title..."' = 'placeholder="@Localizer["Search_Professors"]"'
    'placeholder="Search code, name, department..."' = 'placeholder="@Localizer["Search_Courses"]"'
    'placeholder="Search by name, email or student number..."' = 'placeholder="@Localizer["Students_SearchPlaceholder"]"'
    '<tr><th>Name</th><th>Email</th><th>Title</th><th>Department</th><th>Actions</th></tr>' = '<tr><th>@Localizer["Table_Name"]</th><th>@Localizer["Table_Email"]</th><th>@Localizer["Table_Title"]</th><th>@Localizer["Nav_Departments"]</th><th>@Localizer["Common_Actions"]</th></tr>'
    '<tr><th>Code</th><th>Name</th><th>Semester</th><th>Credits</th><th>Docs</th><th>Department</th><th>Professor</th><th>Actions</th></tr>' = '<tr><th>@Localizer["Table_Code"]</th><th>@Localizer["Table_Name"]</th><th>@Localizer["Table_Semester"]</th><th>@Localizer["Table_Credits"]</th><th>@Localizer["Table_Docs"]</th><th>@Localizer["Nav_Departments"]</th><th>@Localizer["Table_Professor"]</th><th>@Localizer["Common_Actions"]</th></tr>'
    '<tr><th>Student</th><th>Course</th><th>Date</th><th>Actions</th></tr>' = '<tr><th>@Localizer["Table_Student"]</th><th>@Localizer["Table_Course"]</th><th>@Localizer["Table_Date"]</th><th>@Localizer["Common_Actions"]</th></tr>'
    '<tr><th>Student</th><th>Course</th><th>Grade</th><th>Status</th><th>Date</th><th>Actions</th></tr>' = '<tr><th>@Localizer["Table_Student"]</th><th>@Localizer["Table_Course"]</th><th>@Localizer["Table_Grade"]</th><th>@Localizer["Table_Status"]</th><th>@Localizer["Table_Date"]</th><th>@Localizer["Common_Actions"]</th></tr>'
    '<tr><th>Parent</th><th>Email (login)</th><th>Children</th><th>Login</th><th>Actions</th></tr>' = '<tr><th>@Localizer["Table_Parent"]</th><th>@Localizer["Table_Email"] (@Localizer["Table_Login"])</th><th>@Localizer["Table_Children"]</th><th>@Localizer["Table_Login"]</th><th>@Localizer["Common_Actions"]</th></tr>'
    '<thead><tr><th>Department Name</th><th>Actions</th></tr></thead>' = '<thead><tr><th>@Localizer["Table_DepartmentName"]</th><th>@Localizer["Common_Actions"]</th></tr></thead>'
    '<th>Actions</th>' = '<th>@Localizer["Common_Actions"]</th>'
    '<span class="um-badge um-badge-gray">No</span>' = '<span class="um-badge um-badge-gray">@Localizer["Common_No"]</span>'
    '<span class="um-badge um-badge-green">Yes</span>' = '<span class="um-badge um-badge-green">@Localizer["Common_Yes"]</span>'
    'class="btn btn-light border">Cancel</a>' = 'class="btn btn-light border">@Localizer["Common_Cancel"]</a>'
    'onclick="return confirm(''Reset to default password?'');"' = 'onclick="return confirm(''@Localizer["Msg_ResetPasswordConfirm"]'');"'
    '(string.IsNullOrEmpty(p.Title) ? "Professor" : p.Title)' = '(string.IsNullOrEmpty(p.Title) ? Localizer["Default_ProfessorTitle"].Value : p.Title)'
    '<p class="mb-0">No schedules assigned to your courses yet.</p>' = '<p class="mb-0">@Localizer["Msg_NoSchedules"]</p>'
    'No grades yet.' = '@Localizer["Msg_NoGradesYet"]'
    'No requests yet.' = '@Localizer["Msg_NoRequests"]'
    'Submit request' = '@Localizer["Msg_SubmitRequest"]'
    'Back to list' = '@Localizer["Msg_BackToList"]'
    'Back to dashboard' = '@Localizer["Msg_BackToDashboard"]'
}
$files = Get-ChildItem $viewsPath -Recurse -Filter '*.cshtml'
$n = 0
foreach ($file in $files) {
    $c = [System.IO.File]::ReadAllText($file.FullName)
    $o = $c
    foreach ($k in $replacements.Keys) { $c = $c.Replace($k, $replacements[$k]) }
    if ($c -ne $o) {
        [System.IO.File]::WriteAllText($file.FullName, $c, [System.Text.UTF8Encoding]::new($false))
        $n++
    }
}
Write-Host "Updated $n view files."
